project:
  type: website
  output-dir: docs

website:
  title: "Jett Palmer"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - activities.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

