---
title: "Projects"
---

## Client Projects

### Analyzing the Effect of Hand Dominance, Wrist Direction, and Distraction on Ergonomics Task

Evaluated how hand dominance, wrist direction, and distraction affect the time to unscrew a bolt – a task relevant to wrist ergonomics in confined mechanical environments. Carried out an analysis of variance (ANOVA) and power analysis of the blocked, experimental design.

### Associations Between Mothers’ Technology Use, Parenting Stress, and Depression During the Early Postpartum Period

Investigated whether high maternal technology use during infant feeding and care, along with high levels of parenting stress, predict maternal depression at one month postpartum. Implemented multiple logistic and simple linear regression models.

### Investigating Cal Poly Student Sustainability Literacy Using Spatial Data (2025)

Analyzed a survey of sustainability literacy among 876 Cal Poly students, representing all six academic colleges. Assessed how students’ sustainability knowledge, attitudes, and behaviors relate to both geographic characteristics of their home regions and individual demographic factors using two multivariate multiple linear regression models.

### Designing the Premier Student Employment Experience at Cal Poly (2024)

Spearheaded a ten-week survey and analysis that utilized probability sampling and computer-aided personal interviewing (CAPI). Led an 11-person project management team. Under the guidance of Dr. Heather Smith and Cal Poly Student Affairs.

## Presentations

### United By Excellence \| Introducing Sampling Methodology to High School Students (2024)

Interactive presentation to high school students on the 1936 Literary Digest presidential poll: a classic example of flawed statistical sampling.

### Elevating Impact through Data Visualization Workshop (2024)

Taught local nonprofit organizations how to use data visualization to enhance their impact on the community. Under the guidance of Dr. Emily Robinson.

## Legislation

The Associated Students Inc. Board of Directors is the official voice of the student body. As an elected representative, I have authored and passed legislation on the following topics:

### Resolution to Amend ASI Articles of Incorporation (2025)

Passed by the Associated Students Inc. Board of Directors.

### Resolution Calling for Reform of the Course Evaluation Instrument and Processes (2025)

Passed by the Associated Students Inc. Board of Directors.

### Resolution to Reaffirm Shared Governance (2025)

Passed by the Associated Students Inc. Board of Directors.

### Resolution to Recommend an Amendment to the Cal Poly Academic Senate Class Attendance Policy (2024)

Passed by the Associated Students Inc. Board of Directors.
